# Generated by Django 5.0.6 on 2024-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='no image', upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='task',
            name='video',
            field=models.FileField(default='no video', upload_to='media/videos'),
        ),
    ]
