# Generated by Django 5.0.6 on 2024-06-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_image_task_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='no image', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='video',
            field=models.FileField(default='no video', upload_to='media/'),
        ),
    ]
